version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: gastroValencia_postgres
    environment:
      POSTGRES_DB: gastroValencia_db
      POSTGRES_USER: Hector
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
